import { Inter } from "next/font/google";
import "./styled.css"
import Link from "next/link"; 
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <ul>
            <li>
              <Link href="/loyiha/home">Home</Link>
            </li>
            <li>
              <Link href="/loyiha/cartoons">Science_fiction</Link>
            </li>
            <li>
              <Link href="/loyiha/fantasy">Fantasy</Link>
            </li>
            <li>
              <Link href="/loyiha/war">War</Link>
            </li>
            <li>
              <Link href="/loyiha/popular">Trending</Link>
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
